version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend
    expose:
      - "8089"
    environment:
      PORT: 8089
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: justgoit
      DB_PASSWORD: justgoit
      DB_NAME: justgoit
    depends_on:
      - postgres
      - migrate
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: frontend
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
    - ./frontend/deploy/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: justgoit
      POSTGRES_PASSWORD: justgoit
      POSTGRES_DB: justgoit
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  migrate:
    image: migrate/migrate:v4.17.0
    depends_on:
      - postgres
    volumes:
      - ./backend/migrations:/migrations
    entrypoint: >
      sh -c "
      until nc -z postgres 5432; do sleep 2; done;
      migrate -path=/migrations
      -database=postgres://justgoit:justgoit@postgres:5432/justgoit?sslmode=disable
      up
      "

volumes:
  postgres_data:
